[tool.poetry]
name = "voorvoet-app"
version = "0.2.3"
description = "Frontend app to import data from Voorvoet.nl to E-boekhouden.nl."
authors = ["Dennis Bakhuis <git@bakhuis.nu>"]
readme = "README.md"
packages = [{include = "voorvoet_app"}]


[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.5.3"
openpyxl = "^3.1.2"
eboekhouden-python = "0.2.0"
streamlit = "^1.20.0"
tomli = "^2.0.1"
htbuilder = "^0.6.1"


[tool.poetry.group.dev.dependencies]
jupyterlab = "^3.6.3"
pre-commit = "^3.2.2"
pytest = "^7.2.2"
coverage = "^7.2.2"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  ".",
  "./voorvoet_app",
]
